// app/(admin)/reports/page.tsx — Phase 7: Excel + PDF export added
"use client";

import { useState, useEffect, useCallback } from "react";
import { Download, RefreshCw, BarChart3, Users, Clock, TrendingUp, AlertTriangle, FileSpreadsheet, FileText } from "lucide-react";
import { format, startOfMonth, endOfMonth } from "date-fns";
import { BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer, PieChart, Pie, Cell } from "recharts";

const STATUS_COLORS = ["#10b981","#ef4444","#f59e0b","#8b5cf6","#3b82f6","#6b7280"];

export default function ReportsPage() {
  const [period, setPeriod] = useState({ start: format(startOfMonth(new Date()),"yyyy-MM-dd"), end: format(endOfMonth(new Date()),"yyyy-MM-dd") });
  const [summary, setSummary] = useState<any[]>([]);
  const [loading, setLoading] = useState(false);
  const [exporting, setExporting] = useState<string|null>(null);
  const [staff, setStaff] = useState<any[]>([]);
  const [selectedStaff, setSelectedStaff] = useState("");

  useEffect(() => { fetch("/api/admin/options?type=staff").then(r=>r.json()).then(d=>setStaff(d.data||[])); }, []);

  const load = useCallback(async () => {
    setLoading(true);
    const p = new URLSearchParams({ startDate: new Date(period.start).toISOString(), endDate: new Date(period.end+"T23:59:59").toISOString(), limit:"500", ...(selectedStaff?{staffId:selectedStaff}:{}) });
    const res = await fetch(`/api/reports/attendance?${p}`);
    const data = await res.json();
    if (data.success) {
      const grouped: Record<string,any> = {};
      for (const r of data.data.records) {
        const id = r.staff?.id||"unknown";
        if (!grouped[id]) grouped[id] = { name:r.staff?.fullName||"Unknown", employeeId:r.staff?.user?.employeeId||"—", department:r.staff?.department?.name||"—", totalDays:0,presentDays:0,absentDays:0,lateDays:0,earlyLeaveDays:0,overtimeDays:0,totalWorkedH:0,totalOvertimeH:0,totalLateMins:0 };
        const g = grouped[id];
        g.totalDays++;
        if (["PRESENT","LATE","OVERTIME","EARLY_LEAVE","HALF_DAY","OFFLINE_PUNCH","MANUAL_ADJUSTMENT"].includes(r.status)) g.presentDays++;
        if (r.status==="ABSENT") g.absentDays++;
        if (r.status==="LATE") { g.lateDays++; g.totalLateMins+=r.lateMinutes||0; }
        if (r.status==="EARLY_LEAVE") g.earlyLeaveDays++;
        if (r.status==="OVERTIME") { g.overtimeDays++; g.totalOvertimeH+=(r.overtimeMinutes||0)/60; }
        g.totalWorkedH+=(r.totalWorkedMinutes||0)/60;
      }
      setSummary(Object.values(grouped));
    }
    setLoading(false);
  }, [period, selectedStaff]);

  useEffect(() => { load(); }, [load]);

  function dl(blob: Blob, name: string) { const url=URL.createObjectURL(blob); const a=document.createElement("a"); a.href=url; a.download=name; a.click(); URL.revokeObjectURL(url); }

  async function exportFile(fmt: "csv"|"excel"|"payroll-excel"|"pdf") {
    setExporting(fmt);
    try {
      if (fmt==="excel"||fmt==="payroll-excel") {
        const type = fmt==="payroll-excel"?"payroll":"attendance";
        const p = new URLSearchParams({ type, startDate:new Date(period.start).toISOString(), endDate:new Date(period.end+"T23:59:59").toISOString() });
        const res = await fetch(`/api/reports/excel?${p}`);
        dl(await res.blob(), `stafftrack-${type}-${period.start}.xlsx`);
      } else if (fmt==="csv") {
        const p = new URLSearchParams({ format:"csv", startDate:new Date(period.start).toISOString(), endDate:new Date(period.end+"T23:59:59").toISOString() });
        const res = await fetch(`/api/reports/export?${p}`);
        dl(await res.blob(), `attendance-${period.start}.csv`);
      } else if (fmt==="pdf") {
        const p = new URLSearchParams({ type:"summary", startDate:new Date(period.start).toISOString(), endDate:new Date(period.end+"T23:59:59").toISOString() });
        const res = await fetch(`/api/reports/pdf?${p}`);
        const data = await res.json();
        if (data.success) {
          const { default: jsPDF } = await import("jspdf");
          const { default: autoTable } = await import("jspdf-autotable");
          const doc = new jsPDF({ orientation:"landscape", unit:"mm", format:"a4" });
          const pw = doc.internal.pageSize.getWidth();
          doc.setFillColor(15,23,42); doc.rect(0,0,pw,20,"F");
          doc.setTextColor(255,255,255); doc.setFontSize(14); doc.setFont("helvetica","bold");
          doc.text("StaffTrack — Attendance Report", pw/2, 13, { align:"center" });
          doc.setFontSize(9); doc.setFont("helvetica","normal"); doc.setTextColor(148,163,184);
          doc.text(`Period: ${format(new Date(data.data.period.start),"d MMM yyyy")} – ${format(new Date(data.data.period.end),"d MMM yyyy")}  |  Generated by: ${data.data.generatedBy}`, pw/2, 27, { align:"center" });
          autoTable(doc, {
            startY: 35,
            head: [["Emp ID","Name","Department","Present","Absent","Late","Overtime","Total Hrs"]],
            body: data.data.summary.map((s: any) => [s.employeeId,s.fullName,s.department,s.present,s.absent,s.late,s.overtime,s.totalHours.toFixed(1)+"h"]),
            theme:"striped",
            headStyles:{ fillColor:[13,148,136], textColor:255, fontStyle:"bold", fontSize:9 },
            bodyStyles:{ fontSize:8 },
            margin:{ left:10, right:10 },
          });
          doc.save(`stafftrack-report-${period.start}.pdf`);
        }
      }
    } catch(e) { alert("Export failed. Please try again."); }
    finally { setExporting(null); }
  }

  const totals = { staff:summary.length, present:summary.reduce((a,s)=>a+s.presentDays,0), absent:summary.reduce((a,s)=>a+s.absentDays,0), hours:summary.reduce((a,s)=>a+s.totalWorkedH,0), overtime:summary.reduce((a,s)=>a+s.totalOvertimeH,0) };
  const statusChart = [
    { name:"Present", value:totals.present }, { name:"Absent", value:totals.absent },
    { name:"Late", value:summary.reduce((a,s)=>a+s.lateDays,0) },
    { name:"Early Leave", value:summary.reduce((a,s)=>a+s.earlyLeaveDays,0) },
    { name:"Overtime", value:summary.reduce((a,s)=>a+s.overtimeDays,0) },
  ].filter(d=>d.value>0);

  return (
    <div className="p-6 space-y-5">
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <h1 className="text-2xl font-bold text-slate-900 dark:text-white">Reports</h1>
          <p className="text-sm text-slate-500 mt-0.5">Attendance analytics · CSV · Excel · PDF</p>
        </div>
        <div className="flex flex-wrap gap-2">
          {[
            { fmt:"csv",           label:"CSV",          Icon:Download,        cls:"bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-700 text-slate-600 dark:text-slate-300 hover:bg-slate-50" },
            { fmt:"excel",         label:"Excel",        Icon:FileSpreadsheet, cls:"bg-emerald-600 text-white hover:bg-emerald-500 shadow-lg shadow-emerald-500/20" },
            { fmt:"payroll-excel", label:"Payroll XLSX", Icon:FileSpreadsheet, cls:"bg-indigo-600 text-white hover:bg-indigo-500 shadow-lg shadow-indigo-500/20" },
            { fmt:"pdf",           label:"PDF",          Icon:FileText,        cls:"bg-red-600 text-white hover:bg-red-500 shadow-lg shadow-red-500/20" },
          ].map(({fmt,label,Icon,cls})=>(
            <button key={fmt} onClick={()=>exportFile(fmt as any)} disabled={!!exporting} className={`flex items-center gap-2 px-3 py-2 rounded-xl text-sm font-semibold disabled:opacity-60 transition-colors ${cls}`}>
              {exporting===fmt ? <RefreshCw className="w-4 h-4 animate-spin" /> : <Icon className="w-4 h-4" />}{label}
            </button>
          ))}
        </div>
      </div>

      <div className="flex flex-wrap gap-3">
        <input type="date" value={period.start} onChange={e=>setPeriod(p=>({...p,start:e.target.value}))} className="px-3 py-2.5 bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-700 rounded-xl text-sm focus:outline-none focus:ring-2 focus:ring-indigo-500/20" />
        <input type="date" value={period.end}   onChange={e=>setPeriod(p=>({...p,end:e.target.value}))} className="px-3 py-2.5 bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-700 rounded-xl text-sm focus:outline-none focus:ring-2 focus:ring-indigo-500/20" />
        <select value={selectedStaff} onChange={e=>setSelectedStaff(e.target.value)} className="px-3 py-2.5 bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-700 rounded-xl text-sm focus:outline-none focus:ring-2 focus:ring-indigo-500/20">
          <option value="">All staff</option>
          {staff.map((s:any)=><option key={s.id} value={s.id}>{s.fullName}</option>)}
        </select>
        <button onClick={load} className="flex items-center gap-2 px-4 py-2.5 rounded-xl bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-700 text-sm text-slate-600 dark:text-slate-300 hover:bg-slate-50">
          <RefreshCw className={`w-4 h-4 ${loading?"animate-spin":""}`} />Run
        </button>
      </div>

      <div className="grid grid-cols-2 lg:grid-cols-5 gap-4">
        {[
          { icon:Users, label:"Staff", value:totals.staff, c:"text-blue-500" },
          { icon:Users, label:"Present Days", value:totals.present, c:"text-emerald-500" },
          { icon:AlertTriangle, label:"Absent Days", value:totals.absent, c:"text-red-500" },
          { icon:Clock, label:"Total Hours", value:totals.hours.toFixed(1)+"h", c:"text-purple-500" },
          { icon:TrendingUp, label:"OT Hours", value:totals.overtime.toFixed(1)+"h", c:"text-amber-500" },
        ].map(({icon:Icon,label,value,c})=>(
          <div key={label} className="bg-white dark:bg-slate-900 rounded-2xl border border-slate-100 dark:border-slate-800 p-4">
            <Icon className={`w-4 h-4 mb-2 ${c}`} />
            <p className="text-2xl font-bold text-slate-900 dark:text-white">{value}</p>
            <p className="text-xs text-slate-400 mt-0.5">{label}</p>
          </div>
        ))}
      </div>

      {statusChart.length>0 && (
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-5">
          <div className="bg-white dark:bg-slate-900 rounded-2xl border border-slate-100 dark:border-slate-800 p-5">
            <h2 className="text-sm font-semibold text-slate-900 dark:text-white mb-4">Status Distribution</h2>
            <ResponsiveContainer width="100%" height={200}>
              <PieChart><Pie data={statusChart} dataKey="value" nameKey="name" cx="50%" cy="50%" outerRadius={80} label={({name,percent})=>`${name} ${(percent*100).toFixed(0)}%`} labelLine={false}>
                {statusChart.map((_,i)=><Cell key={i} fill={STATUS_COLORS[i%STATUS_COLORS.length]} />)}
              </Pie><Tooltip /></PieChart>
            </ResponsiveContainer>
          </div>
          <div className="bg-white dark:bg-slate-900 rounded-2xl border border-slate-100 dark:border-slate-800 p-5">
            <h2 className="text-sm font-semibold text-slate-900 dark:text-white mb-4">Top Staff Attendance</h2>
            <ResponsiveContainer width="100%" height={200}>
              <BarChart data={summary.slice(0,8).map(s=>({name:s.name.split(" ")[0],days:s.presentDays}))} barSize={20}>
                <CartesianGrid strokeDasharray="3 3" stroke="#f1f5f9" vertical={false} />
                <XAxis dataKey="name" tick={{fontSize:10,fill:"#94a3b8"}} axisLine={false} tickLine={false} />
                <YAxis tick={{fontSize:10,fill:"#94a3b8"}} axisLine={false} tickLine={false} />
                <Tooltip /><Bar dataKey="days" name="Present Days" fill="#6366f1" radius={[4,4,0,0]} />
              </BarChart>
            </ResponsiveContainer>
          </div>
        </div>
      )}

      <div className="bg-white dark:bg-slate-900 rounded-2xl border border-slate-100 dark:border-slate-800 overflow-hidden">
        <div className="px-5 py-4 border-b border-slate-100 dark:border-slate-800 flex items-center gap-2">
          <BarChart3 className="w-4 h-4 text-slate-400" />
          <h2 className="text-sm font-semibold text-slate-900 dark:text-white">Payroll Summary</h2>
          <span className="ml-auto text-xs text-slate-400">{summary.length} staff</span>
        </div>
        <div className="overflow-x-auto">
          <table className="w-full text-sm">
            <thead><tr className="border-b border-slate-100 dark:border-slate-800">
              {["Staff","Dept","Present","Absent","Late","Early","OT Days","OT Hrs","Total Hrs"].map(h=>(
                <th key={h} className="text-left px-4 py-3 text-xs font-semibold text-slate-400 uppercase tracking-wider whitespace-nowrap">{h}</th>
              ))}
            </tr></thead>
            <tbody>
              {loading ? Array.from({length:5}).map((_,i)=>(
                <tr key={i} className="border-b border-slate-50 dark:border-slate-800">
                  {Array.from({length:9}).map((_,j)=><td key={j} className="px-4 py-3"><div className="h-4 skeleton rounded" /></td>)}
                </tr>
              )) : summary.length===0 ? (
                <tr><td colSpan={9} className="px-4 py-10 text-center text-sm text-slate-400">No data for selected period</td></tr>
              ) : summary.map((s,i)=>(
                <tr key={i} className="border-b border-slate-50 dark:border-slate-800 hover:bg-slate-50 dark:hover:bg-slate-800/50">
                  <td className="px-4 py-3"><p className="font-medium text-slate-900 dark:text-white text-sm">{s.name}</p><p className="text-xs text-slate-400">{s.employeeId}</p></td>
                  <td className="px-4 py-3 text-xs text-slate-500">{s.department}</td>
                  <td className="px-4 py-3"><span className="text-emerald-600 dark:text-emerald-400 font-semibold">{s.presentDays}</span></td>
                  <td className="px-4 py-3"><span className={`font-semibold ${s.absentDays>0?"text-red-500":"text-slate-400"}`}>{s.absentDays}</span></td>
                  <td className="px-4 py-3"><span className={`font-semibold ${s.lateDays>0?"text-amber-500":"text-slate-400"}`}>{s.lateDays}</span></td>
                  <td className="px-4 py-3 text-slate-500 text-xs">{s.earlyLeaveDays}</td>
                  <td className="px-4 py-3"><span className={`font-semibold ${s.overtimeDays>0?"text-purple-500":"text-slate-400"}`}>{s.overtimeDays}</span></td>
                  <td className="px-4 py-3 text-slate-600 dark:text-slate-300 text-xs font-mono">{s.totalOvertimeH.toFixed(1)}h</td>
                  <td className="px-4 py-3 font-semibold text-slate-900 dark:text-white font-mono">{s.totalWorkedH.toFixed(1)}h</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
}
